# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Šarm
tagline:          'Tagline o produktu'
description:      'Tukaj nekaj na kratko. '
url:              http://hyde.getpoole.com
baseurl: 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:          [jekyll-paginate]