# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Šarm
tagline:          'Tagline o produktu'
description:      'Primož Mlačnik'
author:           '<strong>Primož Mlačnik</strong> (1990), Dravograjčan, kulturolog in asistent na Fakulteti za družbene vede, 
                  se je prvič rodil v Slovenj Gradcu, kasneje pa tudi v Ljubljani, Santanderju in Luevenu.
                  Zanima ga vez med psihoanalitično teorijo, književnostjo in kulturo.
                  Leta 2014 je za diplomsko delo z naslovom Procesi modernosti v delih Hannah Arendt in Franza Kafke: Eichmann v Jeruzalemu in Proces
                  prejel študentsko Prešernovo nagrado, leta 2016 pa je bila zgodba Tulipanova vest pri reviji Sodobnost 
                  nominirana za najboljšo kratko zgodbo. Od 2015 sodeluje z Danes je nov dan, Inštitutom za druga vprašanja.
                  Primož Mlačnik je dvojček, ljubitelj košarke in glasbene improvizacije.'
fromBook:         'Oprosti, vem, da le tavam v Minotavrovem labirintu. Pišem ti zaradi tvojega romana, romana iz vinjet, 
                  bi rekli lepoumniki, ki sem ga prebral, glej ga zlomka, na isti dan, ko smo šli v talijo. Bravo, Tone, ti mojstritelj, kakšna bravura! Čisto sem ditirambičen 
                  in tudi malo ljubosumen. A limine mi je bilo jasno, zakaj se nisi upal podpisati drugače kot pod psevdonimom.
                  Tvoja Pisateljska liga ostentativno razstira kontroverze, odgrinja kopreno s Satanovega obraza, če se malo pošalim. 
                  Je ironično, ampak ti prav privoščim, da si v istem tednu akceptiral remuneracijo za najboljši roman leta in bil 
                  izvoljen na čelo Mednarodnega pisateljskega sindikata.'
aboutBook:        'Šarm je zbirka dvanajstih kratkih zgodb, v katerih živijo individualisti, ki pričajo o kolektivnih izkušnjah sodobnega Zahodnega
                  sveta. Katalonski profesor prejme darilo za patriotsko držo. Fant s podeželja, ki se mu po žilah pretaka črna kri, je
                  kaznovan. Brezposelni uradnik in rekreativna boksarka nimata ničesar skupnega. V prisluhih voajerskega košarkarja se
                  oglaša glas Gorana Dragića. Nekateri umetniki črpajo motive iz estetike Auschwitza in skatološke proze Petra Travna,
                  drugi pa se navdihujejo pri aferi Flisar. Dva zbegana in razočarana slovenska študenta ne moreta najti svojega mesta
                  na Zemlji. Ona je bolj pismena od Zorana Jankovića in Donalda Trumpa, on pa se sploh ne zaveda svoje (ne)nadarjenosti.
                  Profesor teologije odvrže svoja kulturna očala. Prodajalec rož, ki skrbi, da ljubezen med Evropejci ne bi ugasnila, najde
                  uteho v prepevanju. Breme in blaženost se zgrinjata nad nas!'
order:            'Z nakupom boste podprli predvsem delovanje majhne založbe Cerdonis. Pa avtorja? Avtor je že pred časom izginil v literarni
                  govorici. Govori se, da z malho knjig stoji pred vrati Republike Besed, kjer prosi za azil svojih bralcev.
                  <br>
                  <br> 
                  Cena knjige je 20 evrov skupaj s poštnino.'
url:              https://šarm.info
baseurl: 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://pri-mla.github.io

plugins:          [jekyll-paginate, jekyll-seo-tag]